monolog:
    handlers:
        create_command:
            type:  stream
            path:  '%kernel.logs_dir%/create.log'
            level: info
        restore_command:
            type:  stream
            path:  '%kernel.logs_dir%/restore.log'
            level: info
        show_command:
            type:  stream
            path:  '%kernel.logs_dir%/show.log'
            level: info
    channels:
        - create_command
        - restore_command
        - show_command
